### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by nricsi94** [amidevous/xui.one#1]
File "/root/install.python3", line 253
    os.system("sudo sed -i "s/^license.*/license     =   \"cracked\"/g" /home/xu                                                                                        i/config/config.ini >/dev/null 2>&1")
                            ^
SyntaxError: invalid syntax
finish

**Comment by amidevous** [comment]
yes confirm I sorry update to master version for solve

remove Centos Support

add Ubuntu 24.04 support

or manual solve edit this line and replace

`os.system('sudo sed -i "s/^license.*/license = "cracked"/g" /home/xu i/config/config.ini >/dev/null 2>&1')`

**Comment by amidevous** [comment]
solved i close
