### ISSUE TITLE
could be updated to latest version XUI_1.5.13?

### ISSUE THREAD

**Issue by agaitan026** [amidevous/xui.one#2]
could be updated to latest version XUI_1.5.13? thank you

**Comment by amidevous** [comment]
try change this 

https://update.xui.one/XUI_1.5.12.zip

or

https://github.com/amidevous/xui.one/releases/download/test/XUI_1.5.12.zip

on this

https://update.xui.one/XUI_1.5.13.zip

re add crack

https://github.com/amidevous/xui.one/releases/download/test/xui_crack.tar.gz

no tested

**Comment by amidevous** [comment]
solved with merge

https://github.com/amidevous/xui.one/pull/5/files
